### ISSUE TITLE
Importing pyLOM fails on systems without NVIDIA/ROCm because CuPy is a hard dependency

### ISSUE THREAD

**Issue by fermingut** [ArnauMiro/pyLowOrder#216]
On systems without NVIDIA GPUs (and without ROCm properly configured), installing and using CuPy is not feasible. After the latest changes, `pyLOM` performs a top-level import of `cupy` in the `GAVI` wrapper, which causes

```python
import pyLOM
```

to fail with an `ImportError` when CuPy is not available, even if GPU-related functionality is not required.

**Comment by ArnauMiro** [comment]
I'll take this and fix it ASAP.

**Comment by ArnauMiro** [comment]
@fermingut should be fixed by the latest commit. Pending passing the testsuite and will close the issue.

**Comment by fermingut** [comment]
Thanks for the fix.

However, `import pyLOM` is still failing due to another import in the same wrapper:

```python
from ...utils.parall  import mpi_reduce, pprint, mpi_barrier, MPI_RANK
```

The functions `mpi_reduce` and `mpi_barrier` do not seem to exist in the `pyLOM.utils.parall` module.

**Comment by ArnauMiro** [comment]
Noted, I always mix codes... there are other fixes pending, I'm on it.

**Comment by ArnauMiro** [comment]
@fermingut tests are passing again, I will close this issue as solved.
